# config/settings.py
APP_NAME = "NalencGUI"
APP_CONTEXT = "NalencGUI"
KEY_HEADER = "----BEGIN NAL KEY----"
KEY_FOOTER = "----END NAL KEY----"
EXPECTED_KEY_LEN = 512
MIN_SPLASH_TIME = 3.0

# UI Constants
SPLASH_WIDTH = 430
SPLASH_HEIGHT = 100
MAIN_WINDOW_MIN_WIDTH = 600
MAIN_WINDOW_MIN_HEIGHT = 500
# config/settings.py
APP_NAME = "NalencGUI"
APP_CONTEXT = "NalencGUI"
KEY_HEADER = "----BEGIN NAL KEY----"
KEY_FOOTER = "----END NAL KEY----"
EXPECTED_KEY_LEN = 512
MIN_SPLASH_TIME = 3.0

# UI Constants
SPLASH_WIDTH = 430
SPLASH_HEIGHT = 100
MAIN_WINDOW_MIN_WIDTH = 600
MAIN_WINDOW_MIN_HEIGHT = 500
